spring:
  datasource:
    username: root
    password: Aa-123456
    url: jdbc:mysql://localhost:3306/softwaremanage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 80